source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'whitelabel_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for whitelabel_demo
  pod 'SocketRocket', '0.7.0'
  pod 'MiSnap', '5.5.0'
  pod 'MiSnapUX', '5.5.0'
  pod 'MiSnapFacialCapture', '5.5.0'
  pod 'MiSnapFacialCaptureUX', '5.5.0'
  pod 'MiSnapVoiceCapture', '5.5.0'
  pod 'MiSnapVoiceCaptureUX', '5.5.0'
  pod 'MiSnapNFC', '5.5.0'
  pod 'MiSnapNFCUX', '5.5.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
