source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

#$misnapVersion = '5.10.0'

target 'whitelabel_demo' do

  # MiVIP - will grab nested dependancies
  pod 'MiVIP', '3.8.0'

  # or requred dependancies if using local framework
#   pod 'MiSnap', $misnapVersion
#   pod 'MiSnapUX', $misnapVersion
#   pod 'MiSnapFacialCapture', $misnapVersion
#   pod 'MiSnapFacialCaptureUX', $misnapVersion
#   pod 'MiSnapVoiceCapture', $misnapVersion
#   pod 'MiSnapVoiceCaptureUX', $misnapVersion
#   pod 'MiSnapNFC', $misnapVersion
#   pod 'MiSnapNFCUX', $misnapVersion

end